export const footer = [
  {
    id: 1,
    title: "What's new",
    links: [
      'Surface Duo',
      'Surface Laptop Go',
      'Surface Pro X',
      'Surface Go 2',
      'Surface Book 3',
      'Microsoft 365',
      'Windows 10 apps',
      'HoloLens 2',
    ],
  },
  {
    id: 2,
    title: 'Microsoft Store',
    links: [
      'Account Profile',
      'Download Center',
      'Microsoft Store support',
      'Returns',
      'Order tracking',
      'Virtual workshops and training',
      'Microsoft Store Promise',
      'Financing',
    ],
  },
  {
    id: 3,
    title: 'Education',
    links: [
      'Microsft in education',
      'Office for students',
      'Office 365 for schools',
      'Deals for students & parents',
      'Microsoft Azure in education',
    ],
  },
  {
    id: 4,
    title: 'Enterprise',
    links: [
      'Azure',
      'AppSource',
      'Automotive',
      'Government',
      'Healthcare',
      'Manufacturing',
      'Financial services',
      'Retail',
    ],
  },
  {
    id: 5,
    title: 'Developer',
    links: [
      'Microsoft Visual Studio',
      'Windows Dev Center',
      'Developer Center',
      'Microsoft developer program',
      'Channel 9',
      'Office Dev Center',
      'Microsoft Garage',
    ],
  },
  {
    id: 6,
    title: 'Company',
    links: [
      'Careers',
      'About Microsoft',
      'Company news',
      'Privacy at Microsoft',
      'Investors',
      'Diversity and inclusion',
      'Accessibility',
      'Security',
    ],
  },
]
